version: '3.2'

services:
    php:
        build: config/docker/php
        environment:
            - PARENT_USER_ID
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        entrypoint: ./config/docker/php/docker-entrypoint.sh
    php-zts:
        build: config/docker/php-zts
        environment:
            - PARENT_USER_ID
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
    nginx:
        image: 4xxi/nginx:flex
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
    db:
        image: postgres:9
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
volumes:
    db:
